### ISSUE TITLE
Version of plugin 4.8.0 not compatible with ATAK 4.8.1 (Playstore version)

### ISSUE THREAD

**Issue by Lotus6654** [FreeTAKTeam/FreeTAKMumla_Plugin#2]
Hello, 
I just tested your plugin today with the new ATAK version from the playstore and I get the following message on my Android.

"Ce plugin nécessite une version logicielle 4.8.0.CIV mais vous exécutez: 4.8.1.CIV"

Is there anything special to make it compatible with 4.8.1.CIV ?

**Comment by brothercorvo** [comment]
each ATAK version requires all the plugins to be recompiled, so you can use 4.8 and the plugin or wait for us to compile it
