### ISSUE TITLE
v4.9 transfer.

### ISSUE THREAD

**Issue by almostik** [FreeTAKTeam/FreeTAKMumla_Plugin#3]
Hi, is it planned to move on 4.9 version ?

**Comment by Hellikandra** [comment]
associated to : https://github.com/FreeTAKTeam/FreeTAKMumla_Plugin/pull/4

**Comment by niccellular** [comment]
https://github.com/FreeTAKTeam/FreeTAKMumla_Plugin/releases/tag/0.4.1
